name: Invokable Workflow

on:
  workflow_dispatch:
    inputs:
      applicationUrl:
        type: string
        description: Application URL that is to be tested
      environment:
        type: environment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Check Files
        run: ls
      - name: Run a Script or a command
        run: echo "Hello World"
      - name: Application URL
        run: echo "${{ github.event.inputs.applicationURL }} received from node js server and is it ready to be tested"
